name: Pubish Docker Image

on: workflow_dispatch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
    -
      name: Check out the repo
      uses: actions/checkout@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PAT }}
    -
      name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: dockerfiles/mdsgeospatial_4.1.2.Dockerfile
        push: true
        # tags: meterds/mdsgeospatial:4.1.2
        tags: cstepper/mdsgeospatial:4.1.2
