name: Publish Docker Images Test

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        image: ['r-aws-minimal', 'r-cicd-minimal']
        rversion: ['4.1.2', '4.1.3']
    name: ${{ matrix.image }} - ${{ matrix.rversion }}
    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PAT }}
    -
      name: Create Tags for Docker image
      uses: haya14busa/action-cond@v1
      id: condtag
      with:
        cond: ${{ matrix.rversion == '4.1.3' }}
        if_true: "${{ matrix.image }}:latest, ${{ matrix.image }}:${{ matrix.rversion }}"
        if_false: "${{ matrix.image }}:${{ matrix.rversion }}"
    -
      name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        file: dockerfiles/${{ matrix.image }}_${{ matrix.rversion }}.Dockerfile
        push: true
        tags: ${{ steps.condtag.outputs.value }}
