name: Update Building System

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  execute_R:
    runs-on: ubuntu-latest
    steps:
    -
      name: Check out the repo
      uses: actions/checkout@v2
    -
      name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
    -
      name: Install packages declared in DESCRIPTION
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: local::.
        needs: actions
    -
      name: Extra install sessioninfo
      run: |
        install.packages("sessioninfo")
      shell: Rscript {0}
    -
      name: Run Script
      run: |
        source("execute.R")
      shell: Rscript {0}
    -
      name: Commit changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add --all
        git commit -am "add data"
        git push
