name: Update Building System

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  execute_R:
    runs-on: ubuntu-latest
    steps:
    -
      name: Check out the repo
      uses: actions/checkout@v2
    -
      name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
    # -
    #   name: Restore from renv
    #   uses: r-lib/actions/setup-renv@v1
    -
      name: Install packages declared in DESCRIPTION
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: local::.
        needs: actions
    # -
    #   name: sessioninfo
    #   run: install.packages("sessioninfo", repos = "https://cran.rstudio.com")
    #   shell: Rscript {0}
    -
      name: Run Script
      run: |
        source("execute.R")
      shell: Rscript {0}
    -
      name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
